name: lint-python
on:
 - push
 - pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Linter
        uses: sunnysid3up/python-linter@master
        with:
          source: "engine"
          mypy-options: "--strict --ignore-missing-imports --show-error-codes"
          isort-options: "-w 120"
          black-options: "--line-length 120"
          pylint-options: "-rn -sn --max-line-length=120 --disable=C0111,W0718,W0703,W0511,E0401,C0103"
